---
title: "Clean raw data"
output: html_document
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)

# Load an initial pair of startup functions.
source("R/_startup.R")
# Load necessary libraries; set auto_install = TRUE to try to install any needed packages.
startup(auto_install = FALSE, verbose = FALSE)
# Load all .R files in the R/ subdirectory.
ck37r::load_all_code("R", verbose = TRUE)
```

```{r import_data}

# Import as a data.frame rather than a data.table - avoids extra complication.
data = data.table::fread("data-raw/train.csv", data.table = FALSE)
dim(data)

# examine the structure of the data
names(data) = tolower(names(data))
str(data)
#need this for corellation matrix. converting to numeric s=0 b=1
data$label1 <- ifelse(as.character(data$label) == "s", 0, 1)

# Review classes in our dataset.
table(sapply(data, class))
sapply(data, class)

# Review the number of unique values in each column.
sapply(data, function(col) { length(unique(col)) })

# pri_jet_num has only 4 so let's convert it to a factor.
data$pri_jet_num = as.factor(data$pri_jet_num)
pri_jet_num_table<- table(data$pri_jet_num)
prop.table(pri_jet_num_table)

#       0        1        2        3 
#0.399652 0.310176 0.201516 0.088656
```

```{r data_prep}
# Define our outcome variable.
var_outcome = "label"
# examine the type variable more carefully
data$label = as.factor(data$label)
label_table<- table(data$label)
label_table
# b      s 
#164333  85667
prop.table(label_table)
#b        s 
#0.657332 0.342668



# Specify which variables we don't want to use for prediction.
remove_cols = c(var_outcome,
                # Simply notes that this is all training data.
                "kaggleset",
                # TODO: figure out what these columns mean.
                "eventid", "kaggleweight", "weight")

# Create a list to save our outcome, data, and covariates.
# This can then be used for EDA, modeling, etc.
task = list(
  # Save our primary dataset.
  data = data,
  # Specify which covariates we can use for predicting the outcome
  # (these are only the column names, which can be indexed into task$data).
  covariates = names(data)[!names(data) %in% remove_cols],
  # Specify the outcome vector.
  outcome = as.integer(data[[var_outcome]] == "s")
)

# Review covariates.
task$covariates

# Review outcome distribution.
table(task$outcome, useNA = "ifany")
prop.table(table(task$outcome, useNA = "ifany"))
```

## Missing values

```{r missing_values}
sapply(data, class)
table(is.na(data)) 
head(data)

colMeans(is.na(data))

# Replace -999 values with NA for all of our covariates.
data[, task$covariates] <- lapply(data[, task$covariates], function(col) {
  col[col == -999] <- NA
  col
})
table(is.na(data))
colMeans(is.na(data[, task$covariates]))
head(data)
class(data)
sapply(data, class)

# need to check the proportion of missing for each column

 prop_miss<- apply(data, 2, function(col)sum(is.na(col))/length(col))
 factor(prop_miss)
# der_mass_mmc 0.152456 
 # pri_jet_leading_eta pri_jet_leading_eta pri_jet_leading_phi  0.399652 
 # der_lep_eta_centrality  der_deltaeta_jet_jet  der_mass_jet_jet  der_prodeta_jet_jet 0.709828
  # pri_jet_subleading_eta  pri_jet_subleading_pt pri_jet_subleading_pt  0.709828
 # my guess is the variables in the 2 rows above are highly corelated, they have same percentage of missing. 
# corrrelation matrix
 str(task$covariates)
 
 # guys i can't get this correlation matrix to run. hope you can help me figure out this.
 install.packages("psych")
 

pairs.panels(data.frame[c("DER_mass_MMC", "DER_mass_transverse_met_lep”,  “DER_mass_vis"",
                                          
                   “DER_pt_h”,        “DER_deltaeta_jet_jet”,           “DER_mass_jet_jet“,       “DER_prodeta_jet_jet“,               
         “DER_deltar_tau_lep”,               “DER_pt_tot”,                  “DER_sum_pt”,       “DER_pt_ratio_lep_tau“,
                        
     “DER_met_phi_centrality“,     “DER_lep_eta_centrality“,                 “PRI_tau_pt“,                “PRI_tau_eta“,
                       
                “PRI_tau_phi“,                “PRI_lep_pt“,               “PRI_lep_eta”,                 “PRI_lep_phi”, 
                       
                    “PRI_met”,                “PRI_met_phi”,               “PRI_met_sumet”,                 “PRI_jet_num”, 
                     
        “PRI_jet_leading_pt”,        “PRI_jet_leading_eta”,         “PRI_jet_leading_phi“,      “PRI_jet_subleading_pt“, 
                    
    “PRI_jet_subleading_eta”,      “PRI_jet_subleading_phi”,  “PRI_jet_all_pt“,   “label1”                          )   ])
 


# Add missingness indicators and impute missing values to median.
impute <- ck37r::impute_missing_values(data, type = "standard", verbose = TRUE)

task$data <- impute$data

# Clear out this $data element so that we don't have two copies of the data.
impute$data = NULL

# Add missingness indicators to task$covariates
(task$covariates <- c(task$covariates, impute$indicators_added))

# Confirm that all of our covariates exist in the data.
all(task$covariates %in% names(task$data))

```

## Convert factors to indicators

```{r}

sapply(task$data, class)

# This will only apply to $pri_jet_num
# We need to do the same step on the testing data.
factors = ck37r::factors_to_indicators(data, predictors = task$covariates, verbose = TRUE)
names(factors)

# This is dropping the missingness indicators for some reason - appears to be
# a bug in factors_to_indicators - need to investigate.
names(factors$data)
factors$factor_names

# TODO: this as.vector shouldn't be needed but $factor_names is a column matrix
# (erroneously).
task$data = cbind(task$data, factors$data[, as.vector(factors$factor_names)])
names(task$data)

# Update our covariate list to include the 3 new indicator columns.
(task$covariates = c(task$covariates, as.vector(factors$factor_names)))

# Clear out this extra copy of the dataframe to save memory & storage size.
factors$data = NULL

# Remove $pri_jet_num now that it exists as indicators.
task$data$pri_jet_num = NULL
(task$covariates = setdiff(task$covariates, "pri_jet_num"))
```

## Save results

```{r save_results}

# Confirm that all of our covariates exist in our data.
stopifnot(all(task$covariates %in% names(task$data)))

# Save imputation and factor objects for future reference and use on test dataset.
save(task, impute, factors,
     file = "data/clean.RData")
```
