---
title: "Exploratory data analysis"
output: html_document
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)

# Load an initial pair of startup functions.
source("R/_startup.R")
# Load necessary libraries; set auto_install = TRUE to try to install any needed packages.
startup(auto_install = FALSE, verbose = FALSE)
# Load all .R files in the R/ subdirectory.
ck37r::load_all_code("R", verbose = TRUE)

# File created in clean.Rmd
load("data/clean.RData")

names(task)
task$covariates
```

## Correlation analysis

```{r eda_corr}
corr_data = cbind(task$data[, task$covariates], y = task$outcome)
corr = ck37r::vim_corr(task$covariates, corr_data, "y", bootse = FALSE)

# Look at the correlation of covariates with the outcome.
# Top 20 are incredibly significant.
corr
```

## OLS analysis

```{r eda_reg}
reg = lm(y ~ ., data = x)

# Adj. R-sqr of 0.2464
summary(reg)
```

## Pair-wise analysis

```{r errors=TRUE}
 # guys i can't get this correlation matrix to run. hope you can help me figure out this.
if (F) {
 install.packages("psych")
}

pairs.panels(data.frame[c("DER_mass_MMC", "DER_mass_transverse_met_lep”,  “DER_mass_vis"",
                                          
                   “DER_pt_h”,        “DER_deltaeta_jet_jet”,           “DER_mass_jet_jet“,       “DER_prodeta_jet_jet“,               
         “DER_deltar_tau_lep”,               “DER_pt_tot”,                  “DER_sum_pt”,       “DER_pt_ratio_lep_tau“,
                        
     “DER_met_phi_centrality“,     “DER_lep_eta_centrality“,                 “PRI_tau_pt“,                “PRI_tau_eta“,
                       
                “PRI_tau_phi“,                “PRI_lep_pt“,               “PRI_lep_eta”,                 “PRI_lep_phi”, 
                       
                    “PRI_met”,                “PRI_met_phi”,               “PRI_met_sumet”,                 “PRI_jet_num”, 
                     
        “PRI_jet_leading_pt”,        “PRI_jet_leading_eta”,         “PRI_jet_leading_phi“,      “PRI_jet_subleading_pt“, 
                    
    “PRI_jet_subleading_eta”,      “PRI_jet_subleading_phi”,  “PRI_jet_all_pt“,   “label1”                          )   ])
 
```

## More correlations (and a pretty plot)
```{r corrr}
library(corrr)

m <- dplyr::select(task$data, -c(label, eventid, kaggleset, kaggleweight))
m <- sapply(m,function(x){
  x<-as.numeric(x)

})

corr<- correlate(m)
ke a pretty plot
library(dplyr)
x <- corr %>%
       rearrange(method = "HC", absolute = FALSE) %>%
       shave()

fashion(x)

rplot(x, legend=T)
#need to fix x-axis labels  :(

```

## tSNE

```{r tsne}
library(tsne)
tsne<- tsne(m)
```


## UMAP
```{r umap}

library(umap)

#this is also stalling on my mac! will try running on the server
umaps <- umap(m)

#need to fix this
# plot.custom <- function(x, labels,
#          main="A UMAP visualization",
#          pad=0.1, cex=0.65, pch=19, add=FALSE, legend.suffix="",
#          cex.main=1, cex.legend=1) {
# 
#   layout = x
#   if (class(x)=="umap") {
#     layout = x$layout
#   }
#    xylim = range(layout)
#   xylim = xylim + ((xylim[2]-xylim[1])*pad)*c(-0.5, 0.5)
#   if (!add) {
#     par(mar=c(0.2,0.7,1.2,0.7), ps=10)
#     plot(xylim, xylim, type="n", axes=F, frame=F)
#     rect(xylim[1], xylim[1], xylim[2], xylim[2], border="#aaaaaa", lwd=0.25)
#   }
#   points(layout[,1], layout[,2], col=iris.colors[as.integer(labels)],
#          cex=cex, pch=pch)
#   mtext(side=3, main, cex=cex.main)
#   labels.u = unique(labels)
#   legend.pos = "topright"
#   legend.text = as.character(labels.u)
#   if (add) {
#     legend.pos = "bottomright"
#     legend.text = paste(as.character(labels.u), legend.suffix)
#   }
#   legend(legend.pos, legend=legend.text,
#          col=iris.colors[as.integer(labels.u)],
#          bty="n", pch=pch, cex=cex.legend)
# }
# 
# plot.custom(umaps)
```


## Heat map
```{r heatmap}

heatmap(m)
#not running on my mac, might run on the server..but also the result is similar to the corrr graphic above, no?
```
